title = "Alpaca smart plug Driver"

[network]
ip_address = ""
port = 5_555

[server]
location = "Maybe Somewhere idk"
verbose_driver_exceptions = true

[device]
step_size = 1

    [[device.smartplug]]
    name = "first power strip"
    addr = "localhost:6767"
    driver = "intertech"  # This must match the string in the "supported_devices" dict in switch.py

        [[device.smartplug.outlet]] # 1
        name = "switchname"
        description = "switch one"

        [[device.smartplug.outlet]] # 2
        name = "switchname"
        description = "switch two"

        [[device.smartplug.outlet]] # 3
        name = "switchname"
        description = "switch three"

        [[device.smartplug.outlet]] # 4
        name = "switchname"
        description = "switch four"

        [[device.smartplug.outlet]] # 5
        name = "switchname"
        description = "switch five"

        [[device.smartplug.outlet]] # 6
        name = "switchname"
        description = "switch six"

        [[device.smartplug.outlet]] # 7
        name = "switchname"
        description = "switch seven"

        [[device.smartplug.outlet]] # 8
        name = "switchname"
        description = "switch eight"

    [[device.smartplug]]
    name = "second power strip"
    addr = "localhost:6768"
    driver = "intertech" # This must match the string in the "supported_devices" dict in switch.py

    #  number of outlets is given implicitly, this switch is of size 8
        [[device.smartplug.outlet]] # 1
        name = "switchname"
        description = "switch one"

        [[device.smartplug.outlet]] # 2
        name = "switchname"
        description = "switch two"

        [[device.smartplug.outlet]] # 3
        name = "switchname"
        description = "switch three"

        [[device.smartplug.outlet]] # 4
        name = "switchname"
        description = "switch four"

        [[device.smartplug.outlet]] # 5
        name = "switchname"
        description = "switch five"

        [[device.smartplug.outlet]] # 6
        name = "switchname"
        description = "switch six"

        [[device.smartplug.outlet]] # 7
        name = "switchname"
        description = "switch seven"

        [[device.smartplug.outlet]] # 8
        name = "switchname"
        description = "switch eight"

    [[device.smartplug]]
    name = "third power strip"
    addr = "localhost:6769"
    driver = "epower" # This must match the string in the "supported_devices" dict in switch.py

        [[device.smartplug.outlet]] # 1
        name = "switchname"
        description = "switch one"

        [[device.smartplug.outlet]] # 2
        name = "switchname"
        description = "switch two"

        [[device.smartplug.outlet]] # 3
        name = "switchname"
        description = "switch three"

        [[device.smartplug.outlet]] # 4
        name = "switchname"
        description = "switch four"

[logging]
log_level = "INFO"
log_to_stdout = true
max_size_mb = 5
num_keep_logs = 1
